var EdgesData = [
  {
    "path": "m 281.32748,490.62727 0,-55.05331",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 281.32748,435.57396 -59.599,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 221.72848,435.57396 0,116.67261",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 221.72848,552.24657 296.98485,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 518.71333,552.24657 0,-87.37819",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1156.6247,961.35836 0,90.91374",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1156.6247,1052.2721 -216.17268,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 940.45202,960.85328 0,91.41882",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 940.45202,1052.2721 -56.06347,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,1052.2721 -14.64721,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,1052.2721 0,-105.05588",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,947.21622 -14.14213,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,947.21622 0,-79.29698",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,867.91924 -14.14213,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,867.91924 0,-61.11422",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,806.80502 71.21576,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 955.60431,806.80502 0,30.30458",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 955.60431,806.80502 189.90869,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1145.513,806.80502 0,-28.28427",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1156.6247,1052.2721 56.0634,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.6881,1052.2721 14.6472,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.6881,1052.2721 0,-245.46708",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.6881,806.80502 -67.1751,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,806.80502 0,-254.55845",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1049.5485,552.24657 0,-22.97371",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 940.45202,586.59177 0,-34.3452",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.38855,552.24657 56.06347,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 940.45202,552.24657 109.09648,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1156.6247,587.60192 0,-35.35535",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1156.6247,552.24657 -107.0762,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 281.32748,381.5308 0,54.04316",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 221.72848,435.57396 0,-139.90613",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 221.72848,295.66783 46.9721,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 268.70058,295.66783 0,-13.13198",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 118.92857,435.57396 102.79991,0",
    "name": null,
    "map": "mgu-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 282.59018,490.49727 0,-53.49727",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 282.59018,380.89571 0,56.10429",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 282.59018,437 -60.44732,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.14286,437 0,120.53571",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.14286,557.53571 255.71429,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 477.85715,557.53571 0,48.11895",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.14286,437 0,-142.85715",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.14286,294.14285 255.71429,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 477.85715,294.14285 0,-13.75731",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 477.85715,294.14285 103.48564,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 581.34279,294.14285 0,-12.24208",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,960.72328 0,30.80965",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,991.53293 -54.04316,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,991.53293 0,-254.05337",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,737.47956 -16.16245,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,737.47956 0,-98.48987",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,638.98969 -16.16245,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,991.53293 215.16245,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1155.1094,991.53293 0,-30.80965",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1155.1094,991.53293 58.8192,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1213.9286,991.53293 0,-352.54324",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1213.9286,638.98969 15.4271,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1213.9286,638.98969 0,-81.45398",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1155.1094,587.47191 0,-29.9362",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1155.1094,557.53571 58.8192,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,638.98969 0,-81.45398",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,587.47191 0,-29.9362",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 885.90379,557.53571 54.04316,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,557.53571 0,-32.69326",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 939.94695,557.53571 118.18785,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1058.1348,557.53571 0,-32.18818",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1059.1449,557.53571 95.9645,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1213.9286,557.53571 0,-205.53571",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1213.9286,352 16.7857,0",
    "name": null,
    "map": "mgu-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 280.31733,493.02265 0,-58.8798",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 280.31733,380.92857 0,53.21428",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 280.31733,434.14285 -58.08377,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.23356,434.14285 0,-140.62533",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.23356,293.51752 118.18785,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 340.42141,293.51752 0,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 340.42141,293.51752 0,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 340.42141,293.51752 0,-13.38452",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 340.42141,293.51752 109.09647,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 449.51788,293.51752 0,-13.13198",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.23356,434.14285 0,135.65139",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 222.23356,569.79424 662.66007,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 941.46217,569.79424 -56.56854,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 941.46217,587 0,-17.20576",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 941.46217,569.79424 111.57353,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1053.0357,569.79424 0,-44.9371",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1053.0357,569.79424 101.5687,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,569.79424 0,19.34862",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,569.79424 57.5787,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,569.79424 0,-87.79424",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 1212.1831,482 1230,482.71429",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,482.71429 0,-127.14286",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,355.57143 15.674,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,354.14286 0,-60.62534",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,293.51752 47.8169,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 1260,293.51752 1260,282",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,293.51752 -57.5787,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,293.51752 0,-12.58895",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,293.51752 -101.5687,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1053.0357,293.51752 0,-12.23181",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1053.0357,293.51752 -168.14207,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.89363,293.51752 -54.17934,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 830.47166,293.51752 0,-9.97525",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 829.10385,293.51752 -379.58268,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.89363,293.51752 0,276.27672",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.89363,569.79424 0,421.73869",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 884.89363,991.53293 56.56854,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 941.46217,991.53293 0,-31.67579",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 941.46217,991.53293 213.14223,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,991.53293 0,-29.53293",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1154.6044,991.53293 57.5787,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,991.53293 0,46.18137",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,991.53293 0,-242.39007",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,749.85714 17.1026,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,749.14286 0,-65.70646",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,683.4364 18.174,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,683.4364 0,-80.72211",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,602.71429 17.8169,0",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1212.1831,601.28571 0,-31.49147",
    "name": null,
    "map": "mgu-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  }
];
