var EdgesData = [
  {
    "path": "m 1217.7734,773.78515 -189.6484,-0.0977 0,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1028.125,773.6875 0,-147.65625",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1028.125,626.03125 -140.03906,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,773.6875 0,209.375",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,983.0625 117.1875,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1461.7188,983.0625 0,40.2344",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1461.7188,983.0625 397.6562,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1859.375,983.0625 0,50.3906",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,773.6875 0,-318.75",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,454.9375 187.5,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1532.0313,454.9375 0,-45.7637",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,454.9375 0,-61.23166",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1218.6543,773.77574 76.235,-0.0882",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1294.8893,773.6875 49.642,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1294.8893,773.68275 0,-150.54699",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1344.5313,773.6875 152.2701,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1294.8893,621.92969 0,-94.81268",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1294.8893,527.11701 81.0873,0",
    "name": null,
    "map": "mosfilm-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 895.71429,2966.4286 -64.06406,-61.9221",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 831.29445,2904.8637 452.14909,3285.4562",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 452.14909,3285.4562 279.59776,3110.966",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 264.07698,3067.3322 30.03016,-8.4036",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 279.59776,3110.966 -15.52078,-43.6338",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 264.07698,3067.3322 -12.64841,-35.5588",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 279.59776,3110.966 -17.46317,17.7471",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,3031.7734 0,-105.3448",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2926.4286 -27.93232,0",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2926.4286 0,-363.5715",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2562.8571 29.39384,0",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2562.8571 0,-288.5714",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2274.2857 28.38369,0",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,2274.2857 0,-689.2857",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,1585 27.37353,0",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 251.42857,1585 0,-976.94583",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 251.42857,608.05417 283.32321,500.2723",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 283.32321,500.2723 577.76964,215.86362",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "M 577.73401,215.89803 555.5839,194.72501",
    "name": null,
    "map": "mosfilm-2-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1398.0714 0,-77.14",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1320.9314 -23.31189,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1320.9314 0,-40.9111",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1280.0203 24.90239,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1280.0203 0,-101.5204",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1178.4999 24.54525,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1178.4999 0,-125.764",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1052.7359 23.83097,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,1052.7359 0,-88.89339",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,963.84251 -21.88332,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,963.84251 0,-35.86042",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,927.98209 23.47382,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,927.98209 0,-354.05847",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,573.92362 -21.71828,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,573.92362 23.23351,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,573.92362 0,-76.77159",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,497.15203 24.24366,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,497.15203 0,-75.25633",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,421.8957 24.74874,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,421.8957 0,-68.1853",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,353.7104 -22.72843,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,353.7104 25.25382,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,353.7104 0,-68.1853",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,285.5251 -21.2132,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,285.5251 25.75889,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,285.5251 0,-61.1143",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,224.4108 -22.72843,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,224.4108 0,-62.6294",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,161.7814 25.25382,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 286.88332,161.7814 -22.72843,0",
    "name": null,
    "map": "mosfilm-5-3",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 725.71429,112.46428 0,154.10715",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 725.71429,266.57143 82.66029,0",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 808.37458,266.57143 0,-58.21429",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 725.71429,266.57143 -171.42858,0",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 554.28571,266.57143 0,23.57143",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 554.28571,266.57143 -300,0",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 254.28571,266.57143 0,142.85714",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 254.28571,409.42857 -24.28571,0",
    "name": null,
    "map": "mosfilm-6-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 95.459416,268.27907 500.025514,0",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 595.48493,268.27907 0,-29.29443",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 595.48493,268.27907 152.02795,0",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.51288,268.27907 0,-29.29443",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.51288,268.27907 63.13454,0",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 810.64742,268.27907 0,-61.11423",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 810.64742,268.27907 138.3909,0",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 949.03832,268.27907 0,-29.29443",
    "name": null,
    "map": "mosfilm-6-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 41.668793,377.76639 231.072397,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 272.74119,377.76639 0,14.39467",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 272.74119,377.76639 121.2183,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 393.95949,377.76639 0,13.63706",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 393.95949,377.76639 192.43406,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 586.39355,377.76639 0,-68.69037 0,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 586.39355,309.07602 266.68027,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 853.07382,309.07602 11.11168,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 864.1855,309.07602 0,-55.79031",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 864.1855,253.28571 -23.11407,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 864.1855,254 0,-47.14286",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 853.07382,611.6167 -13.63705,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 853.07382,611.67857 0,-34.82143",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 925.35714,576.85714 -72.28332,0",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 853.07382,576.85714 0,-267.78112",
    "name": null,
    "map": "mosfilm-7-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1259.2857,761.25881 -54.1737,0",
    "name": null,
    "map": "mosfilm-7-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1205.112,761.25881 0,-218.68738",
    "name": null,
    "map": "mosfilm-7-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1205.112,542.57143 -777.96914,0",
    "name": null,
    "map": "mosfilm-7-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1205.112,542.57143 0,-334.87621",
    "name": null,
    "map": "mosfilm-7-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1205.112,207.69522 -51.5178,0",
    "name": null,
    "map": "mosfilm-7-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 580.33263,145.19203 0,75.1301",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 580.33263,220.32213 -22.09708,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 580.33263,220.32213 0,103.54063",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 580.33263,323.86276 -174.75639,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 405.57624,323.86276 0,395.85153",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 405.57624,719.71429 -16.66751,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 580.33263,323.86276 161.09594,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 741.42857,323.86276 0,45.49439",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 741.42857,323.86276 325.71433,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1067.1429,323.86276 0,395.85153",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1067.1429,719.71429 19.2762,0",
    "name": null,
    "map": "mosfilm-18-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 503.92857,219.53571 -20.53571,0",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 483.39286,219.53571 0,72.32143",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 483.39286,291.85714 125.35714,0",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 608.75,291.85714 0,-42.32143",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 608.75,291.85714 268.21429,0",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 876.96429,291.85714 0,-47.85714",
    "name": null,
    "map": "mosfilm-18-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 695.49003,627.07143 0,32.40186",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 695.49003,627.07143 -76.26652,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 619.22351,627.07143 0,20.53257",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 619.22351,627.07143 -234.9378,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 384.28571,627.07143 0,-13.30754",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 695.49003,627.07143 0,-79.28572",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 695.49003,627.07143 80.30712,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 775.79715,627.07143 15.98857,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 775.79715,627.07143 0,-133.01062",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 775.79715,494.06081 314.91715,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1090.7143,494.06081 0,16.58205",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1090.7143,494.06081 161.4286,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1252.1429,494.06081 28.5714,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1252.1429,494.06081 0,188.63562",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1252.1429,682.69643 13.2142,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1280.7143,494.06081 0,-139.13224",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1280.7143,354.92857 17.5,0",
    "name": null,
    "map": "mosfilm-27-1",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 600.40942,650.82143 0,-20.26375",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 600.40942,630.55768 -343.26656,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 257.14286,644.03571 0,-13.47803",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 600.40942,630.55768 146.73344,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.14286,630.55768 0,-70.83695",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.14286,559.72073 -25.89394,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.14286,559.46819 0,-62.03962",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.14286,497.42857 -18.57143,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 728.57143,497.42857 0,-22.05558",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 728.57143,497.42857 -62.14286,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 666.42857,497.42857 0,-68.57143",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 666.42857,428.85714 -155.03884,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 511.38973,428.85714 0,103.57143",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 511.38973,532.42857 -101.38973,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 410,532.42857 0,-10.58856",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 410,532.42857 -210,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 200,532.42857 0,-10.58856",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 747.14286,497.42857 142.85714,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 890,497.42857 0,-22.14286",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 890,497.42857 178.5714,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1068.5714,497.42857 0,-21.42857",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1068.5714,497.42857 207.8572,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1276.4286,497.42857 0,-68.57143",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  },
  {
    "path": "m 1276.4286,428.85714 17.8571,0",
    "name": null,
    "map": "mosfilm-27-2",
    "objectId": 0,
    "bgColor": null,
    "opacity": 1.0,
    "borderColor": null,
    "borderWidth": 0.0,
    "borderJoin": null,
    "borderCap": null,
    "text": null,
    "align": null,
    "x": 0.0,
    "y": 0.0,
    "angle": 0.0,
    "scaleX": 0.0,
    "scaleY": 0.0,
    "fontSize": 0.0,
    "fontFamily": null,
    "fontWeight": null,
    "color": null,
    "matrix": null
  }
];
